# Generated by Django 5.2.9 on 2026-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_transaction_id_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
